spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:booking_testing_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306/booking_testing_db
    user: root
    password: root
    baseline-on-migrate: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
logging:
  level:
    org.springframework.orm.hibernate5.SQL: debug
    org.springframework.orm.hibernate5.type.descriptor.sql.BasicBinder: trace

