-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------

-- Drop the rooms table if it exists
DROP TABLE IF EXISTS booking_testing_db.products;

-- Create products table
CREATE TABLE booking_testing_db.products (
                                             product_id BIGINT PRIMARY KEY AUTO_INCREMENT,
                                             name VARCHAR(45) NOT NULL,
                                             description VARCHAR(255),
                                             unit_of_measurement VARCHAR(20),
                                             price DECIMAL(7, 2) NOT NULL
);

-- Insert products into products table
INSERT INTO booking_testing_db.products (name, description, unit_of_measurement, price)
VALUES
    ('Shampoo', 'Hair care product', 'Bottle', 5.99),
    ('Soap', 'Body wash soap', 'Bar', 1.49),
    ('Toothpaste', 'Mint flavored toothpaste', 'Tube', 2.99),
    ('Towel', 'Cotton bath towel', 'Piece', 10.00),
    ('Bed Sheet', 'King size bed sheet', 'Set', 25.00),
    ('Pillow', 'Soft cotton pillow', 'Piece', 15.00),
    ('Blanket', 'Warm woolen blanket', 'Piece', 30.00),
    ('Toothbrush', 'Soft bristle toothbrush', 'Piece', 1.00),
    ('Conditioner', 'Hair conditioner', 'Bottle', 6.49),
    ('Body Lotion', 'Moisturizing body lotion', 'Bottle', 8.99),
    ('Face Wash', 'Gentle face wash', 'Bottle', 4.99),
    ('Slippers', 'Comfortable indoor slippers', 'Pair', 5.50),
    ('Bathrobe', 'Soft cotton bathrobe', 'Piece', 20.00),
    ('Shaving Cream', 'Foaming shaving cream', 'Tube', 3.99),
    ('Razor', 'Disposable razor', 'Piece', 2.50),
    ('Laundry Bag', 'Cloth laundry bag', 'Piece', 2.00),
    ('Hair Dryer', 'Portable hair dryer', 'Piece', 25.00),
    ('Iron', 'Steam iron', 'Piece', 30.00),
    ('Ironing Board', 'Foldable ironing board', 'Piece', 15.00),
    ('Hand Sanitizer', 'Alcohol based hand sanitizer', 'Bottle', 3.00),
    ('Shower Cap', 'Plastic shower cap', 'Piece', 0.50),
    ('Cotton Buds', 'Pack of 100 cotton buds', 'Pack', 1.00),
    ('Nail Clippers', 'Stainless steel nail clippers', 'Piece', 2.00),
    ('Body Scrub', 'Exfoliating body scrub', 'Jar', 6.00),
    ('Deodorant', 'Antiperspirant deodorant', 'Stick', 4.00),
    ('Room Spray', 'Fresh linen room spray', 'Bottle', 5.00),
    ('Face Towel', 'Small cotton face towel', 'Piece', 2.00),
    ('Sewing Kit', 'Mini sewing kit', 'Kit', 1.00),
    ('Mouthwash', 'Mint mouthwash', 'Bottle', 2.50),
    ('Eye Mask', 'Silk sleep eye mask', 'Piece', 5.00),
    ('Ear Plugs', 'Noise-canceling ear plugs', 'Pair', 1.00),
    ('Bath Salts', 'Relaxing bath salts', 'Bag', 7.00),
    ('Body Oil', 'Nourishing body oil', 'Bottle', 10.00),
    ('Bath Mat', 'Anti-slip bath mat', 'Piece', 8.00),
    ('Shower Gel', 'Refreshing shower gel', 'Bottle', 4.50),
    ('Hair Brush', 'Detangling hair brush', 'Piece', 3.00),
    ('Comb', 'Fine-tooth comb', 'Piece', 1.50),
    ('Lip Balm', 'Hydrating lip balm', 'Tube', 2.00),
    ('Face Mask', 'Rejuvenating face mask', 'Piece', 3.00),
    ('Hand Cream', 'Soothing hand cream', 'Tube', 3.50),
    ('Foot Cream', 'Revitalizing foot cream', 'Tube', 4.00),
    ('Travel Adapter', 'Universal travel adapter', 'Piece', 10.00),
    ('USB Charger', 'Portable USB charger', 'Piece', 12.00),
    ('Power Bank', 'High capacity power bank', 'Piece', 20.00),
    ('Notebook', 'Lined notebook', 'Piece', 2.00),
    ('Pen', 'Ballpoint pen', 'Piece', 1.00),
    ('Pencil', 'Mechanical pencil', 'Piece', 1.50),
    ('Marker', 'Permanent marker', 'Piece', 2.00),
    ('Stapler', 'Mini stapler', 'Piece', 3.00),
    ('Paper Clips', 'Box of paper clips', 'Box', 1.00),
    ('Sticky Notes', 'Pack of sticky notes', 'Pack', 2.00),
    ('Scissors', 'Stainless steel scissors', 'Piece', 3.00),
    ('Tape', 'Roll of adhesive tape', 'Roll', 1.00),
    ('Envelopes', 'Pack of envelopes', 'Pack', 2.00),
    ('Calculator', 'Portable calculator', 'Piece', 5.00),
    ('Flashlight', 'LED flashlight', 'Piece', 6.00),
    ('Batteries', 'Pack of AA batteries', 'Pack', 4.00),
    ('Umbrella', 'Compact umbrella', 'Piece', 10.00),
    ('Backpack', 'Lightweight backpack', 'Piece', 20.00),
    ('Duffel Bag', 'Travel duffel bag', 'Piece', 25.00),
    ('Suitcase', 'Medium size suitcase', 'Piece', 50.00),
    ('Travel Pillow', 'Neck support travel pillow', 'Piece', 15.00),
    ('Luggage Tag', 'Personalized luggage tag', 'Piece', 3.00),
    ('Travel Wallet', 'RFID blocking travel wallet', 'Piece', 12.00),
    ('Passport Holder', 'Leather passport holder', 'Piece', 10.00),
    ('Sunglasses', 'UV protection sunglasses', 'Piece', 20.00),
    ('Reading Glasses', 'Magnifying reading glasses', 'Piece', 15.00),
    ('Watch', 'Digital wristwatch', 'Piece', 30.00),
    ('Bracelet', 'Leather bracelet', 'Piece', 8.00),
    ('Necklace', 'Silver pendant necklace', 'Piece', 20.00),
    ('Earrings', 'Gold stud earrings', 'Pair', 15.00),
    ('Ring', 'Sterling silver ring', 'Piece', 25.00),
    ('Cufflinks', 'Designer cufflinks', 'Pair', 30.00),
    ('Belt', 'Leather belt', 'Piece', 20.00),
    ('Wallet', 'Bifold leather wallet', 'Piece', 25.00),
    ('Handbag', 'Fashionable handbag', 'Piece', 40.00),
    ('Socks', 'Pair of cotton socks', 'Pair', 5.00),
    ('T-shirt', 'Graphic print T-shirt', 'Piece', 15.00),
    ('Jeans', 'Denim jeans', 'Piece', 40.00),
    ('Jacket', 'Waterproof jacket', 'Piece', 60.00),
    ('Sweater', 'Woolen sweater', 'Piece', 30.00),
    ('Shoes', 'Running shoes', 'Pair', 50.00),
    ('Boots', 'Leather boots', 'Pair', 70.00),
    ('Sandals', 'Beach sandals', 'Pair', 20.00),
    ('Hat', 'Baseball cap', 'Piece', 10.00),
    ('Scarf', 'Woolen scarf', 'Piece', 15.00),
    ('Gloves', 'Winter gloves', 'Pair', 12.00),
    ('Tie', 'Silk tie', 'Piece', 20.00),
    ('Suit', 'Business suit', 'Set', 150.00),
    ('Dress', 'Evening dress', 'Piece', 100.00),
    ('Skirt', 'Pleated skirt', 'Piece', 30.00),
    ('Blouse', 'Silk blouse', 'Piece', 40.00),
    ('Jumpsuit', 'Casual jumpsuit', 'Piece', 50.00),
    ('Swimsuit', 'One-piece swimsuit', 'Piece', 25.00),
    ('Shorts', 'Cargo shorts', 'Piece', 20.00),
    ('Cap', 'Snapback cap', 'Piece', 15.00),
    ('Belt', 'Braided belt', 'Piece', 10.00);


